apiVersion: v1
kind: Service
metadata:
  name: my-jhttp-svc
  labels:
    app: jhttp 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: jhttp 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jhttp
  labels:
    app: jhttp 
spec:
  replicas:1 
  selector:
    matchLabels:
      app: jhttp 
  template:
    metadata:
      labels:
        app: jhttp 
    spec:
      containers:
      - name: jhttp 
        image: <+artifact.image> 
        ports:
        - containerPort: 80
